### ISSUE TITLE
Now we are ready to create our Flow Definition!

### ISSUE THREAD

**Issue by timwukp** [aws-samples/amazon-a2i-sample-jupyter-notebooks#43]
in notebook of Amazon Augmented AI (A2I) and Textract AnalyzeDocument
when run 
# Flow definition name - this value is unique per account and region. You can also provide your own value here.
uniqueId = str(uuid.uuid4())
print(uniqueId)
flowDefinitionName = f'fd-textract-{uniqueId}' 
print (flowDefinitionName)
flowDefinitionArn = create_flow_definition(flowDefinitionName)
print (flowDefinitionArn)

The error happened, 

ClientError: An error occurred (ValidationException) when calling the CreateFlowDefinition operation: 1 validation error detected: Value 'arn:aws:sagemaker:ap-southeast-1:xxxxxxxxxxxx:flow-definition/a2idemotextract' at 'humanLoopConfig.workteamArn' failed to satisfy constraint: Member must satisfy regular expression pattern: arn:aws[a-z\-]*:sagemaker:[a-z0-9\-]*:[0-9]{12}:workteam/.*

Is there any problem?

**Comment by timwukp** [comment]
solved, my bad

**Comment by Jaden-Dz99** [comment]
For anyone that has stumbled across this problem, the solution was to double-check the WORKTEAM_ARN -  it's quite easy to overlook this as ARN's match the regex provided
